source 'https://rubygems.org'

gem 'jekyll'

group :jekyll_plugins do
    gem 'github-pages'
    gem 'jekyll-email-protect'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end